import { Product, Batch, Coupon, SystemSettings } from '../models/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Premium Basmati Rice",
    brand: "India Gate",
    category: "Grocery",
    subCategory: "Grains & Rice",
    description: "Extra long grain select basmati rice, pristine flavor and premium texture. Perfect for all biryanis and special occasions.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 142,
    seoKeywords: "basmati rice, long grain rice, india gate, biryani rice",
    specifications: {
      "Origin": "India",
      "Grain Length": "8.3mm",
      "Shelf Life": "24 Months",
      "Food Category": "Vegetarian",
    },
    variants: [
      { id: "var-1a", name: "1kg Bag", sku: "IG-BR-1K", barcode: "890123410011", stock: 0 },
      { id: "var-1b", name: "5kg Bag", sku: "IG-BR-5K", barcode: "890123410059", stock: 0 },
    ],
  },
  {
    id: "prod-2",
    name: "Organic Toor Dal",
    brand: "Tata Sampann",
    category: "Grocery",
    subCategory: "Pulses & Lentils",
    description: "Unpolished, uncompromised, protein-rich yellow split peas certified organic. Sourced from native organic farms.",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=600",
    rating: 4.5,
    reviewsCount: 88,
    seoKeywords: "toor dal, yellow lentils, arhar dal, organic lentils",
    specifications: {
      "Origin": "India",
      "Polished": "No",
      "Grade": "A Grade",
      "Organic": "Yes",
    },
    variants: [
      { id: "var-2a", name: "1kg pouch", sku: "TS-TD-1K", barcode: "890234510012", stock: 0 },
    ],
  },
  {
    id: "prod-3",
    name: "Gold Standard Sunflower Oil",
    brand: "Fortune",
    category: "Grocery",
    subCategory: "Edible Oils",
    description: "Light, healthy, refined sunflower oil enriched with Vitamins A & D. High smoke point ideal for native frying.",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 205,
    seoKeywords: "sunflower oil, edible oil, cooking oil, low fat oil",
    specifications: {
      "Refined Type": "Physical",
      "Fortified": "Vitamin A & D",
      "Volume": "1 Litre",
    },
    variants: [
      { id: "var-3a", name: "1L Bottle", sku: "FT-SO-1L", barcode: "890345610013", stock: 0 },
      { id: "var-3b", name: "5L Can", sku: "FT-SO-5L", barcode: "890345610051", stock: 0 },
    ],
  },
  {
    id: "prod-4",
    name: "Fresh Whole Milk",
    brand: "Amul Taaza",
    category: "Daily Essentials",
    subCategory: "Dairy Products",
    description: "Pasteurized homogenized toning whole milk, delicious taste, zero preservatives. Sourced fresh daily.",
    image: "/src/assets/images/regenerated_image_1780689036107.jpg",
    rating: 4.9,
    reviewsCount: 520,
    seoKeywords: "milk, amul milk, dairy, whole milk, pasteurized milk",
    specifications: {
      "Fat Content": "3.5% Min",
      "SNF Content": "8.5% Min",
      "Pasteurized": "Yes",
      "Unit": "500ml Pack",
    },
    variants: [
      { id: "var-4a", name: "500ml Pouch", sku: "AM-MK-500", barcode: "890456710014", stock: 0 },
      { id: "var-4b", name: "1L Carton", sku: "AM-MK-1L", barcode: "890456710021", stock: 0 },
    ],
  },
  {
    id: "prod-5",
    name: "Multigrain Brown Bread",
    brand: "Harvest Gold",
    category: "Daily Essentials",
    subCategory: "Bakery & Breads",
    description: "High-fiber brown bread loaded with wholesome barley, cracked wheat, and millet. Oven fresh arrival.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600",
    rating: 4.4,
    reviewsCount: 310,
    seoKeywords: "brown bread, harvest bread, wheat bread, healthy bread",
    specifications: {
      "Weight": "400g",
      "Whole Wheat": "70% Min",
      "Added Preservatives": "Within safe limits",
    },
    variants: [
      { id: "var-5a", name: "400g Pack", sku: "HG-BB-400", barcode: "890567810015", stock: 0 },
    ],
  },
  {
    id: "prod-6",
    name: "Powerful Dishwashing Liquid",
    brand: "Vim Gel",
    category: "Household Esports",
    subCategory: "Cleaners",
    description: "Concentrated lemon cleaner formulation that targets greasiness in seconds and leaves zero chalky residue.",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 198,
    seoKeywords: "vim gel, dishwashing liquid, lemon cleaning, vessel cleaner",
    specifications: {
      "Scent": "Lemon Splash",
      "Volume": "500ml",
      "pH balanced": "Yes",
    },
    variants: [
      { id: "var-6a", name: "500ml Squeeze", sku: "VM-DL-500", barcode: "890678910016", stock: 0 },
      { id: "var-6b", name: "1L Refill", sku: "VM-DL-1L", barcode: "890678910023", stock: 0 },
    ],
  },
  {
    id: "prod-7",
    name: "Gentle Herbal Shampoo",
    brand: "Kesh King",
    category: "Personal Care",
    subCategory: "Hair Care",
    description: "Enriched with 21 medicinal Ayurvedic herbs. Clinically text-proven to reduce hairfall and boost thickness.",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80&w=600",
    rating: 4.3,
    reviewsCount: 95,
    seoKeywords: "herbal shampoo, kesh king, hairfall control, ayurvedic shampoo",
    specifications: {
      "Type": "Ayurvedic Proprietary Medicine",
      "Key Ingredient": "Bhringraj, Amla, Neem",
      "Quantity": "300ml",
    },
    variants: [
      { id: "var-7a", name: "300ml Bottle", sku: "KK-HS-300", barcode: "890789010017", stock: 0 },
    ],
  },
  {
    id: "prod-8",
    name: "Spicy Instant Masala Noodles",
    brand: "Maggi",
    category: "Packaged Foods",
    subCategory: "Snacks & Noodles",
    description: "Everyone's favorite 2-minute snack instant masala noodles. Infused with 12 aromatic roasted spices.",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 1250,
    seoKeywords: "maggi, instant noodles, quick snack, spicy noodles, 2-minute maggi",
    specifications: {
      "Pack Count": "12 Units Single Pack",
      "Noodle Type": "Refined Wheat",
      "With Tastemaker": "Yes",
    },
    variants: [
      { id: "var-8a", name: "Pack of 12", sku: "MG-MN-P12", barcode: "890890110018", stock: 0 },
      { id: "var-8b", name: "Single Pack", sku: "MG-MN-SGL", barcode: "890890110022", stock: 0 },
    ],
  },
  {
    id: "prod-9",
    name: "Rich Sandalwood Soap",
    brand: "Mysore Sandal",
    category: "Personal Care",
    subCategory: "Skin Care",
    description: "The original formulation with natural pure Sandalwood Almond Oil extraction. Keeps skin glowing and fresh.",
    image: "https://images.unsplash.com/photo-1607006342411-10078988a873?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 380,
    seoKeywords: "mysore sandal, sandalwood soap, herbal soap, bath bar",
    specifications: {
      "Sandaloil Quantity": "0.8%",
      "TFM Value": "80% (Grade 1)",
      "Unit Weight": "150g",
    },
    variants: [
      { id: "var-9a", name: "150g Bar", sku: "MS-SO-150", barcode: "890901210019", stock: 0 },
      { id: "var-9b", name: "Pack of 3", sku: "MS-SO-P3", barcode: "890901210033", stock: 0 },
    ],
  },
  {
    id: "prod-10",
    name: "Classic Tomato Ketchup",
    brand: "Kissan",
    category: "Packaged Foods",
    subCategory: "Sauces & Spreads",
    description: "Made from 100% real juicy vine-ripened tomatoes. Rich, glossy texture that is a perfect companion to crispy snacks.",
    image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 145,
    seoKeywords: "tomato ketchup, kissan sauce, tomato sauce",
    specifications: {
      "Net Weight": "950g",
      "Bottle Type": "Squeezy",
    },
    variants: [
      { id: "var-10a", name: "950g Squeezy Bottle", sku: "KS-TK-950", barcode: "890912310020", stock: 0 },
    ],
  }
];

export const INITIAL_BATCHES: Batch[] = [
  // Basmati Rice (prod-1, var-1a/var-1b)
  {
    id: "BAT-BR-001",
    productId: "prod-1",
    variantId: "var-1a",
    purchasePrice: 90,
    sellingPrice: 120,
    quantity: 15,
    initialQuantity: 50,
    mfgDate: "2026-01-10",
    expiryDate: "2028-01-10",
    taxPercent: 5,
    hsnCode: "10063010",
    supplier: "Dev Giri Farms Ltd",
    isActive: true,
  },
  {
    id: "BAT-BR-002",
    productId: "prod-1",
    variantId: "var-1a",
    purchasePrice: 95,
    sellingPrice: 125,
    quantity: 35,
    initialQuantity: 80,
    mfgDate: "2026-03-05",
    expiryDate: "2028-03-05",
    taxPercent: 5,
    hsnCode: "10063010",
    supplier: "Madan Grain Traders",
    isActive: false, // Inactive because it is chronological FIFO queue
  },
  {
    id: "BAT-BR-5K-001",
    productId: "prod-1",
    variantId: "var-1b",
    purchasePrice: 420,
    sellingPrice: 550,
    quantity: 12,
    initialQuantity: 20,
    mfgDate: "2026-02-15",
    expiryDate: "2028-02-15",
    taxPercent: 5,
    hsnCode: "10063010",
    supplier: "Dev Giri Farms Ltd",
    isActive: true,
  },

  // Organic Toor Dal (prod-2, var-2a)
  {
    id: "BAT-TD-001",
    productId: "prod-2",
    variantId: "var-2a",
    purchasePrice: 130,
    sellingPrice: 175,
    quantity: 2, // LOW STOCK alert
    initialQuantity: 30,
    mfgDate: "2025-11-20",
    expiryDate: "2026-11-20",
    taxPercent: 5,
    hsnCode: "07133100",
    supplier: "Vidarbha Agro Org",
    isActive: true,
  },
  {
    id: "BAT-TD-002",
    productId: "prod-2",
    variantId: "var-2a",
    purchasePrice: 135,
    sellingPrice: 180,
    quantity: 40,
    initialQuantity: 40,
    mfgDate: "2026-04-01",
    expiryDate: "2027-04-01",
    taxPercent: 5,
    hsnCode: "07133100",
    supplier: "Vidarbha Agro Org",
    isActive: false, // FIFO reserve
  },

  // Sunflower Oil (prod-3, var-3a/var-3b)
  {
    id: "BAT-SO-001",
    productId: "prod-3",
    variantId: "var-3a",
    purchasePrice: 105,
    sellingPrice: 140,
    quantity: 22,
    initialQuantity: 60,
    mfgDate: "2025-10-10",
    expiryDate: "2026-10-10",
    taxPercent: 12,
    hsnCode: "15121910",
    supplier: "Adani Wilmar Refineries",
    isActive: true,
  },
  {
    id: "BAT-SO-5L-001",
    productId: "prod-3",
    variantId: "var-3b",
    purchasePrice: 510,
    sellingPrice: 670,
    quantity: 0, // OUT OF STOCK test
    initialQuantity: 15,
    mfgDate: "2025-08-01",
    expiryDate: "2026-08-01",
    taxPercent: 12,
    hsnCode: "15121910",
    supplier: "Adani Wilmar Refineries",
    isActive: true,
  },

  // Fresh Whole Milk (prod-4, var-4a/var-4b)
  {
    id: "BAT-MK-001",
    productId: "prod-4",
    variantId: "var-4a",
    purchasePrice: 21,
    sellingPrice: 28,
    quantity: 18,
    initialQuantity: 100,
    mfgDate: "2026-06-02",
    expiryDate: "2026-06-04", // EXPIRING SOON
    taxPercent: 0,
    hsnCode: "04012000",
    supplier: "Amul Anand Cooperative",
    isActive: true,
  },
  {
    id: "BAT-MK-1L-001",
    productId: "prod-4",
    variantId: "var-4b",
    purchasePrice: 42,
    sellingPrice: 56,
    quantity: 8,
    initialQuantity: 50,
    mfgDate: "2026-06-02",
    expiryDate: "2026-06-04", // EXPIRING TOMORROW
    taxPercent: 0,
    hsnCode: "04012000",
    supplier: "Amul Anand Cooperative",
    isActive: true,
  },

  // Bread (prod-5, var-5a)
  {
    id: "BAT-BR-400-001",
    productId: "prod-5",
    variantId: "var-5a",
    purchasePrice: 32,
    sellingPrice: 45,
    quantity: 1, // LOW STOCK AND EXPIRING SOON
    initialQuantity: 25,
    mfgDate: "2026-05-30",
    expiryDate: "2026-06-04", // June 4th
    taxPercent: 0,
    hsnCode: "19059090",
    supplier: "Harvest Fresh Bakers",
    isActive: true,
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: "RUDRAX20",
    discountPercent: 20,
    minOrderValue: 500,
    description: "Get 20% off on all premium orders above ₹500",
    isActive: true,
    expiryDate: "2026-12-31"
  },
  {
    code: "FRESH30",
    discountPercent: 30,
    minOrderValue: 200,
    description: "Special launch discount: 30% off up to ₹150!",
    isActive: true,
    expiryDate: "2026-07-15"
  },
  {
    code: "ESSENTIALS10",
    discountPercent: 10,
    minOrderValue: 100,
    description: "Flat 10% off for daily pantry essential items",
    isActive: true,
    expiryDate: "2026-09-30"
  }
];

export const INITIAL_SETTINGS: SystemSettings = {
  storeName: "Rudrax Superstore",
  contactEmail: "support@rudrax.com",
  supportPhone: "+1 (800) RDX-FRESH",
  defaultTaxRate: 5,
  freeShippingThreshold: 499,
  standardShippingFee: 40,
  loyaltyPointsPerDollar: 5
};
